-- --------------- CLIENT 100 ENTRÉES ---------------
INSERT IGNORE INTO CLIENT (ID_CLIENT, NOM_CLI, PRENOM_CLI, EMAIL_CLI, MDP_CLI, TEL_CLI, STATUT_CLI)
SELECT NULL,
    CONCAT('Nom', LPAD(FLOOR(1 + RAND()*1000),3,'0')),
    CONCAT('Prenom', LPAD(FLOOR(1 + RAND()*1000),3,'0')),
    CONCAT('user', LPAD(FLOOR(1 + RAND()*1000),3,'0'),'@mail.com'),
    'password123',
    CONCAT('+33', FLOOR(600000000 + RAND() * 399999999)),
    ELT(FLOOR(1 + RAND() * 4), 'normal','admin','inactif','partenaire')
FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1,
     (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2;

-- --------------- ACTIVITE_EVENEMENT 100 ENTRÉES ---------------
INSERT IGNORE INTO ACTIVITE_EVENEMENT 
(ID_ACT_EV, NOM, DESCRIPTION_CMPLT, DESCRIPTION_COURTE, TYPE_ACT_EVENT, DATE_DEBUT, DATE_FIN, ID_CLIENT_ORGANISATEUR, PRIX, CAPACITE, PUBLIC_CIBLE, DIFFICULTE, NOTE_MOYENNE, TAGS)
SELECT NULL,
    CONCAT('Activité ', LPAD(FLOOR(1 + RAND()*1000),3,'0')),
    'Description complète générée automatiquement pour test',
    'Desc courte',
    ELT(FLOOR(1 + RAND() * 2), 'activite','evenement'),
    NOW() + INTERVAL FLOOR(RAND()*60) DAY,
    NOW() + INTERVAL FLOOR(RAND()*60 + 1) DAY,
    FLOOR(1 + RAND() * 100),
    ROUND(RAND()*200,2),
    FLOOR(5 + RAND()*50),
    ELT(FLOOR(1 + RAND() * 3), 'enfant','adulte','tous'),
    ELT(FLOOR(1 + RAND() * 3), 'facile','moyen','difficile'),
    ROUND(RAND()*5,2),
    'tag1,tag2,tag3'
FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1,
     (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2;

-- --------------- IMAGE_ACTIVITE 2 IMAGES PAR ACTIVITÉ ---------------
INSERT IGNORE INTO IMAGE_ACTIVITE (ID_ACT_EV, URL_IMAGE)
SELECT ID_ACT_EV, 'uploads/1760971649_Capture d’écran du 2025-05-04 21-09-58.png' FROM ACTIVITE_EVENEMENT;

INSERT IGNORE INTO IMAGE_ACTIVITE (ID_ACT_EV, URL_IMAGE)
SELECT ID_ACT_EV, 'uploads/1760352267_Capture d’écran du 2025-06-02 20-08-11.png' FROM ACTIVITE_EVENEMENT;

-- --------------- PARTICIPATION 100 ENTRÉES ---------------
INSERT IGNORE INTO PARTICIPATION (ID_PARTICIPATION, ID_ACT_EV, DATE_JOUR_ACTI, PRIX_TOTAL, STATUT_PART)
SELECT NULL,
    FLOOR(1 + RAND()*100),
    NOW() + INTERVAL FLOOR(RAND()*60) DAY,
    ROUND(RAND()*300,2),
    ELT(FLOOR(1 + RAND()*4), 'en_attente', 'confirmee', 'annulee', 'terminee')
FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1,
     (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2;

-- --------------- PARTICIPANT 100 ENTRÉES ---------------
INSERT IGNORE INTO PARTICIPANT (ID_PARTICIPATION, ID_CLIENT)
SELECT 
    FLOOR(1 + RAND()*100),
    FLOOR(1 + RAND()*100)
FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1,
     (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2;

-- --------------- FAVORIS 100 ENTRÉES ---------------
INSERT IGNORE INTO FAVORIS (ID_CLIENT, ID_ACT_EV)
SELECT 
    FLOOR(1 + RAND()*100),
    FLOOR(1 + RAND()*100)
FROM (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t1,
     (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
      UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) t2;
