<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


try {
    $db = new PDO("mysql:host=localhost;dbname=travel_db;charset=utf8", "appuser", "monmdp");
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // === Création automatique des tables si elles n'existent pas ===
    $db->exec("
    CREATE TABLE IF NOT EXISTS CLIENT (
        ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
        NOM_CLI VARCHAR(255) NOT NULL,
        PRENOM_CLI VARCHAR(255) NOT NULL,
        EMAIL_CLI VARCHAR(255) NOT NULL UNIQUE,
        MDP_CLI VARCHAR(255) NOT NULL,
        TEL_CLI VARCHAR(50) NOT NULL,
        STATUT_CLI ENUM('normal','admin','inactif','partenaire') NOT NULL DEFAULT 'normal',
        PHOTO_PROFILE VARCHAR(255) NOT NULL DEFAULT './photos/profilpic/profiledefault.jpg'
    );");

    $db->exec("
    CREATE TABLE IF NOT EXISTS ACTIVITE (
        ID_ACTIVITE INT AUTO_INCREMENT PRIMARY KEY,
        NOM_ACT VARCHAR(255) NOT NULL,
        DESCRIPTION_ACT TEXT,
        LIEU_ACT VARCHAR(255) NOT NULL,
        DATE_DEBUT_ACT DATE NOT NULL,
        DATE_FIN_ACT DATE,
        ID_CLIENT_ORGANISATEUR INT NOT NULL,
        FOREIGN KEY (ID_CLIENT_ORGANISATEUR) REFERENCES CLIENT(ID_CLIENT)
            ON DELETE CASCADE ON UPDATE CASCADE
    );");

    $db->exec("
    CREATE TABLE IF NOT EXISTS EVENEMENT (
        ID_EVENEMENT INT AUTO_INCREMENT PRIMARY KEY,
        NOM_EVT VARCHAR(255) NOT NULL,
        DESCRIPTION_EVT TEXT,
        LIEU_EVT VARCHAR(255) NOT NULL,
        DATE_DEBUT_EVT DATE NOT NULL,
        DATE_FIN_EVT DATE,
        ID_CLIENT_ORGANISATEUR INT NOT NULL,
        FOREIGN KEY (ID_CLIENT_ORGANISATEUR) REFERENCES CLIENT(ID_CLIENT)
            ON DELETE CASCADE ON UPDATE CASCADE
    );");

    $db->exec("
    CREATE TABLE IF NOT EXISTS PARTICIPATION (
    ID_PARTICIPATION INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT INT NOT NULL,
    ID_ACTIVITE INT,
    ID_EVENEMENT INT,
    DATE_PARTICIPATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE(ID_ACTIVITE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_EVENEMENT) REFERENCES EVENEMENT(ID_EVENEMENT)
        ON DELETE CASCADE ON UPDATE CASCADE
);");

} catch(PDOException $e) {
    die("Erreur connexion ou création des tables : " . $e->getMessage());
}
