
-- 1️⃣ Création de la base
CREATE DATABASE IF NOT EXISTS travel_db;
USE travel_db;

-- Nettoyage des anciennes tables
DROP TABLE IF EXISTS PARTICIPANT;
DROP TABLE IF EXISTS PARTICIPATION;
DROP TABLE IF EXISTS ACTIVITE_EVENEMENT;
DROP TABLE IF EXISTS CLIENT;

-- 6️⃣ Table CLIENT
CREATE TABLE CLIENT (
    ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CLI VARCHAR(100) NOT NULL,
    PRENOM_CLI VARCHAR(100) NOT NULL,
    EMAIL_CLI VARCHAR(150) NOT NULL UNIQUE,
    MDP_CLI VARCHAR(255) NOT NULL,
    TEL_CLI VARCHAR(20),
    STATUT_CLI ENUM('normal','admin','inactif','partenaire') NOT NULL DEFAULT 'normal',
    PHOTO_PROFILE VARCHAR(255) NOT NULL DEFAULT './photos/profilpic/profiledefault.jpg'
);

CREATE INDEX idx_client_email ON CLIENT(EMAIL_CLI);

-- 7️⃣ Table ACTIVITE_EVENEMENT
CREATE TABLE ACTIVITE_EVENEMENT (
    ID_ACT_EV INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(150) NOT NULL,
    DESCRIPTION_CMPLT TEXT,
    DESCRIPTION_COURTE VARCHAR(255),
    TYPE_ACT_EVENT ENUM('activite','evenement') NOT NULL,
    DATE_DEBUT DATETIME NOT NULL,
    DATE_FIN DATETIME,
    ID_CLIENT_ORGANISATEUR INT NOT NULL,
    PRIX DECIMAL(10,2) DEFAULT 0,
    CAPACITE INT DEFAULT NULL,
    PUBLIC_CIBLE ENUM('enfant','adulte','tous') DEFAULT 'tous',
    DIFFICULTE ENUM('facile','moyen','difficile') DEFAULT 'facile',
    IMAGES VARCHAR(255) DEFAULT './photos/defaut.jpg',
    NOTE_MOYENNE DECIMAL(3,2) DEFAULT NULL,
    TAGS VARCHAR(255) DEFAULT NULL,
    FOREIGN KEY (ID_CLIENT_ORGANISATEUR) REFERENCES CLIENT(ID_CLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (DATE_FIN IS NULL OR DATE_FIN >= DATE_DEBUT)
);

CREATE INDEX idx_activite_evenement_date ON ACTIVITE_EVENEMENT(DATE_DEBUT);
CREATE INDEX idx_activite_evenement_type ON ACTIVITE_EVENEMENT(TYPE_ACT_EVENT);
CREATE INDEX idx_activite_evenement_client ON ACTIVITE_EVENEMENT(ID_CLIENT_ORGANISATEUR);

-- 8️⃣ Table PARTICIPATION (réservation principale)
CREATE TABLE PARTICIPATION (
    ID_PARTICIPATION INT AUTO_INCREMENT PRIMARY KEY,
    ID_ACT_EV INT NOT NULL,
    DATE_JOUR_ACTI DATETIME NULL,
    DATE_PARTICIPATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIX_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0,
    STATUT_PART ENUM('en_attente', 'confirmee', 'annulee', 'terminee') NOT NULL DEFAULT 'en_attente',
    FOREIGN KEY (ID_ACT_EV) REFERENCES ACTIVITE_EVENEMENT(ID_ACT_EV)
        ON DELETE CASCADE
);

CREATE INDEX idx_participation_actev ON PARTICIPATION(ID_ACT_EV);
CREATE INDEX idx_participation_statut ON PARTICIPATION(STATUT_PART);

-- 9️⃣ Table PARTICIPANT (clients liés à une participation)
CREATE TABLE PARTICIPANT (
    ID_PARTICIPATION INT,
    ID_CLIENT INT,
    PRIMARY KEY (ID_PARTICIPATION, ID_CLIENT),
    FOREIGN KEY (ID_PARTICIPATION) REFERENCES PARTICIPATION(ID_PARTICIPATION)
        ON DELETE CASCADE,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
        ON DELETE CASCADE
);

CREATE INDEX idx_participant_client ON PARTICIPANT(ID_CLIENT);

