-- 1️⃣ Crée la base
CREATE DATABASE IF NOT EXISTS travel_db;
USE travel_db;

-- 2️⃣ Supprime l'utilisateur s'il existe
DROP USER IF EXISTS 'appuser'@'localhost';

-- 3️⃣ Crée l'utilisateur avec mot de passe compatible PHP
CREATE USER 'appuser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'monmdp';

-- 4️⃣ Donne tous les privilèges sur la base
GRANT ALL PRIVILEGES ON travel_db.* TO 'appuser'@'localhost';
FLUSH PRIVILEGES;

-- 5️⃣ Création des tables

DROP TABLE IF EXISTS PARTICIPATION;
DROP TABLE IF EXISTS EVENEMENT;
DROP TABLE IF EXISTS ACTIVITE;
DROP TABLE IF EXISTS CLIENT;

-- Table CLIENT
CREATE TABLE CLIENT (
    ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CLI VARCHAR(255) NOT NULL,
    PRENOM_CLI VARCHAR(255) NOT NULL,
    EMAIL_CLI VARCHAR(255) NOT NULL UNIQUE,
    MDP_CLI VARCHAR(255) NOT NULL,
    TEL_CLI VARCHAR(50) NOT NULL,
    STATUT_CLI ENUM('normal','admin','inactif','partenaire') NOT NULL DEFAULT 'normal',
    PHOTO_PROFILE VARCHAR(255) NOT NULL DEFAULT './photos/profilpic/profiledefault.jpg'
);

-- Table ACTIVITE
CREATE TABLE ACTIVITE (
    ID_ACTIVITE INT AUTO_INCREMENT PRIMARY KEY,
    NOM_ACT VARCHAR(255) NOT NULL,
    DESCRIPTION_ACT TEXT,
    LIEU_ACT VARCHAR(255) NOT NULL,
    DATE_DEBUT_ACT DATE NOT NULL,
    DATE_FIN_ACT DATE,
    ID_CLIENT_ORGANISATEUR INT NOT NULL,
    FOREIGN KEY (ID_CLIENT_ORGANISATEUR) REFERENCES CLIENT(ID_CLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table EVENEMENT
CREATE TABLE EVENEMENT (
    ID_EVENEMENT INT AUTO_INCREMENT PRIMARY KEY,
    NOM_EVT VARCHAR(255) NOT NULL,
    DESCRIPTION_EVT TEXT,
    LIEU_EVT VARCHAR(255) NOT NULL,
    DATE_DEBUT_EVT DATE NOT NULL,
    DATE_FIN_EVT DATE,
    ID_CLIENT_ORGANISATEUR INT NOT NULL,
    FOREIGN KEY (ID_CLIENT_ORGANISATEUR) REFERENCES CLIENT(ID_CLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table PARTICIPATION
CREATE TABLE PARTICIPATION (
    ID_PARTICIPATION INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT INT NOT NULL,
    ID_ACTIVITE INT,
    ID_EVENEMENT INT,
    DATE_PARTICIPATION DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITE(ID_ACTIVITE)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_EVENEMENT) REFERENCES EVENEMENT(ID_EVENEMENT)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK ((ID_ACTIVITE IS NOT NULL AND ID_EVENEMENT IS NULL) OR 
           (ID_ACTIVITE IS NULL AND ID_EVENEMENT IS NOT NULL))
);
